### ISSUE TITLE
Suggestion: Replace this with standard combat mission

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/TRRF#1]
I suggest that we dont use training mission red forces.
I think it is better if we replace it with the standard combat mission I am making. The intention is the same, have a framework to set up combat events with a minimum effort.

This way we have one mission for training where we dont use red forces, and one mission for combat, with red forces.

**Comment by 132nd-etcher** [comment]
This is only a dummy repository I created to illustrate the guide I sent you =)

**Comment by 132ndNeck** [comment]
Ah, copy. I did not recive any guide though?
